### ISSUE TITLE
Move to our instance of overpass?

### ISSUE THREAD

**Issue by aarthykc** [geohacker/shaktiman#9]
Since @geohacker created our own instance of overpass, maybe we could get shaktiman to point to our instance instead? 

cc @geohacker, @batpad, @arunasank

**Comment by geohacker** [comment]
@aarthykc great idea, but what we should do is make this configurable as a parameter and default to the original overpass instance when nothing is specified. 

PRs wellcommee!

**Comment by geohacker** [comment]
Fixed in #14 
Thank you @aarthykc
